name="backend"
compatibility_date = "2024-06-20"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNTdkNjFkNzktYmY2ZS00MDZlLWE0NTAtNzU2MTI1MDc2OWM5IiwidGVuYW50X2lkIjoiMDcwOTViZmM2MjAyMWYwZWE4MDNkZWY5NTg1NzJjYTQ2ZjVjY2EwYmE5ZDJlNjFlMGVhNWU4ZGJhZmYyOTZlNiIsImludGVybmFsX3NlY3JldCI6IjE2MDViN2U2LTVlN2YtNGZiMi05N2VjLTllYTMyNWM2YThiZCJ9.AE0SrjKIJ9jn_pP0fYNZTUiPcpfDfZYIFlwm9AOMhpE"

JWT_SECRET="eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcxODk0NDEwMywiaWF0IjoxNzE4OTQ0MTAzfQ.H6prf3VBSNjzbkM7IyOdUWGynL87GV7KaanX8-IVUrI"